// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPlatformAPI.Web.Data;

namespace WebPlatformAPI.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191209000306_alterCustumer")]
    partial class alterCustumer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebPlatformAPI.Web.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addres")
                        .HasMaxLength(20);

                    b.Property<string>("BirthDate")
                        .HasMaxLength(10);

                    b.Property<string>("CivilStatus")
                        .HasMaxLength(20);

                    b.Property<string>("Company")
                        .HasMaxLength(100);

                    b.Property<float>("CreditLimit");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Gender")
                        .HasMaxLength(1);

                    b.Property<string>("Idinternal");

                    b.Property<string>("Job")
                        .HasMaxLength(60);

                    b.Property<string>("LastName")
                        .HasMaxLength(60);

                    b.Property<string>("Name")
                        .HasMaxLength(60);

                    b.Property<string>("Nationality")
                        .HasMaxLength(60);

                    b.Property<string>("Passport")
                        .HasMaxLength(20);

                    b.Property<string>("RNC")
                        .HasMaxLength(20);

                    b.Property<string>("Telephone")
                        .HasMaxLength(14);

                    b.Property<string>("Telephone1")
                        .HasMaxLength(14);

                    b.Property<string>("Telephone2")
                        .HasMaxLength(14);

                    b.Property<string>("Telephone3")
                        .HasMaxLength(14);

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
